<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVPX9s2r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVPX9s2r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVPX9s2r.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVPX9s2r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVPX9s2r\App_KernelDevDebugContainer([
    'container.build_hash' => 'VPX9s2r',
    'container.build_id' => '11f0cfc2',
    'container.build_time' => 1650669080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVPX9s2r');
